# Sample configuration file for gnssstreamer CLI utility.
# This outputs the data stream to a TCP socket server.
# Usage:
#    gnssstreamer -C gnssstreamer.conf
# Or set environment variable GNSSSTREAMER_CONF to
# location of this file and simply run:
#    gnssstreamer
## gnssstreamer.conf
# port=/dev/ttyACM0
# filename=/data/gnssdata.bin
# {userName:"sxbwoi4uv3u902lgsh0d",password:"qimlk7naxbr8awgw4p2x"}
socket=localhost:50013
verbosity=3
timeout=120
clioutput=6
output=mqtt://sxbwoi4uv3u902lgsh0d:qimlk7naxbr8awgw4p2x@spoorwiel-vm-02.westeurope.cloudapp.azure.com:1883
format=1
protfilter=1
msgfilter=GNRMC,GNGGA,GPRMC,GPGGA