# Sample configuration file for gnssstreamer CLI utility.
# This outputs the data stream to a TCP socket server.
# Usage:
#    gnssstreamer -C gnssstreamer.conf
# Or set environment variable GNSSSTREAMER_CONF to
# location of this file and simply run:
#    gnssstreamer
## gnssstreamer.conf
# port=/dev/ttyACM0
# filename=/data/gnssdata.bin
socket=localhost:50012
verbosity=3
timeout=120
clioutput=6
output=mqtt://hcq88h53t715xo5kaepu:twwj2koa9x70tnqtipf2@spoorwiel-vm-02.westeurope.cloudapp.azure.com:1883?client_id=rp5-04-gps
format=1
protfilter=1
msgfilter=GNRMC,GNGGA,GPRMC,GPGGA