# Sample configuration file for gnssstreamer CLI utility.
# This outputs the data stream to a TCP socket server.
# Usage:
#    gnssstreamer -C gnssstreamer.conf
# Or set environment variable GNSSSTREAMER_CONF to
# location of this file and simply run:
#    gnssstreamer
## gnssstreamer.conf
# port=/dev/ttyACM0
# filename=/data/gnssdata.bin
socket=localhost:50011
verbosity=3
timeout=120
clioutput=6
output=mqtt://h0voh0j5mebfmq869o9k:88xp1yrghwop7h4syerf@spoorwiel-vm-02.westeurope.cloudapp.azure.com:1883?client_id=rp5-03-gps
format=1
protfilter=1
msgfilter=GNRMC,GNGGA,GPRMC,GPGGA